### PR TITLE
Adds blog page and styles

### PR DESCRIPTION
**Pull request by amitg01**

### CODE REVIEW

**Comment by srijan-kapoor** [comment]
@n1c01a5 Could you take a look at this? Thank you

**Comment by n1c01a5** [comment]
@srijan-kapoor looks good

**Comment by n1c01a5** [comment]
@amitg01 I think there is some style side effect of the font style especially the size. Can you check?

**Comment by bhavesh92pandey** [comment]
here some list of changes as discussed with Nicolas on the Blog page

- Text on Buttons (header and footer) not the same size. Should be:  https://recover-website.vercel.app/
- Need linearity of blog design on the left and right - Design alignment 
- For the text design, there should be more spacing on the interior - https://material.io/components/cards

**Comment by amitg01** [comment]
@n1c01a5 @bhavesh92pandey I have made the suggested changes. Please review.

**Comment by bhavesh92pandey** [comment]
Yes, looks good now. We can proceed with Blog 1 and Blog 2 integration

**Comment by amitg01** [comment]
@bhavesh92pandey Can you please merge this PR, so that I can rebase the branch I've created for the 10th issue with master.

**Comment by bhavesh92pandey** [comment]
I have added a Task in the shared Goole sheet to integrate the Blog page with the new design. For reference please see blog.kleros.io

**Pull request merged**
