### PR TITLE
[WIP]Modifies blog page

### LINKED ISSUE #21: Fix Blog Page - Task  12 Google sheet
- Fix the Blog page. Follow the design mentioned in Figma. 

- For reference, we want the Blog page to work like Kleros. Example: blog.Kleros.io. The recent blog should be on the cover of the page while the rest of the articles should be placed below like mentioned. 

- The padding should follow medium.com articles

- The font should be in sync with Recover website 

- Google sheet link: https://docs.google.com/spreadsheets/d/1x76BTbLm9dpUixjRy43NlEZJfgvPiMtH6QLg66fAmYA/edit#gid=0

- Add photograph on the cover of Blog page 

Figma Link: https://www.figma.com/file/a4C0WETqHQR4siSgnRNnn1b7/RECOVER?node-id=0%3A1

### PR DESCRIPTION
**Pull request by amitg01**
fixes #21

### CODE REVIEW

**Comment by bhavesh92pandey** [comment]
Hi @amitg01 
The page looks good. The mobile view looks good too. Just a few comments
1. Maybe for the desktop view, we can go with less spacing on the sides and symmetrically arrange it with the design like done in Figma 
2. The title of the first blog (recently added) can be a little on the top (like Kleros) unlike being on center

**Comment by bhavesh92pandey** [comment]
Hi @amitg01,

Any update on the changes?

**Comment by amitg01** [comment]
The changes will be done by E.O.D today.

**Comment by amitg01** [comment]
@bhavesh92pandey I have made the necessary changes. And for the background image of the main section, I am attaching screenshots of the main section with all the four different images you sent me. Please let me know which one do you prefer.

Screenshot 2020-12-06 at 12 48 55 AM  

*****************************************************************************

Screenshot 2020-12-06 at 12 50 31 AM

*****************************************************************************

Screenshot 2020-12-06 at 12 49 09 AM

*****************************************************************************

Screenshot 2020-12-06 at 12 49 44 AM

**Comment by bhavesh92pandey** [comment]
Hi @amitg01 

The changes made look better now and the photograph you attached as the cover is good. But as I can see, the spacing is still more when compared with the home page. Can you please check this?

**Comment by bhavesh92pandey** [comment]
Hi @amitg01 

Please find the attached screenshots for changes. 
Screen Shot 2020-12-06 at 1 21 21 PM
Screen Shot 2020-12-06 at 1 22 06 PM

**Comment by amitg01** [comment]
Hi @bhavesh92pandey. I think the deployment was somehow delayed and it showed you the stale version. Please check the deployment link again and let me know if you like the newer changes.

**Pull request merged**
